// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvllpqinpoxoscpgigmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2bGxwcWlucG94b3NjcGdpZ213Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MDQ4OTIsImV4cCI6MjA3Njk4MDg5Mn0.oZ-OvaBbQJr8Kb6YQfeiLQ0x1vK3maEY5LkVDR6EsYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});